<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\spEditor.ico</ApplicationIcon>
	<Platforms>x64</Platforms>
	  <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SharedParametersDefinitionFile.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Parameters.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Parameters.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="Syncfusion.SfGrid.WPF" Version="32.*" />

	<PackageReference Include="Serilog" Version="4.3.0" />

	<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
	<PackageReference Include="Serilog.Sinks.GoogleAnalytics" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedParametersDefinitionFile\SharedParametersDefinitionFile.csproj" />
  </ItemGroup>

</Project>